name: env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - ipython
  - jupyter
  - conda-build
  - scikit-learn
  - pip:
    - tensorflow
    - tensorflow-probability

  # install locally with:
  # conda env create --prefix ./.conda -f .conda_environment.yml  

  # Activate envornment with:
  # conda activate ./.conda
  # Add do-mpc:
  # conda develop /PATH/TO/do-mpc
